### ISSUE TITLE
Support CONSUL_HTTP_ADDR environment

### ISSUE THREAD

**Issue by jcheyer** [segmentio/consul-go#46]
it would be nice if the package would support CONSUL_HTTP_ADDR environment var by default to avoid unnecessary code like this:
```
r := consul.DefaultResolver
r.Client = consul.DefaultClient
r.Client.Address = envy.Get("CONSUL_HTTP_ADDR", consul.DefaultAddress)
http.DefaultTransport = httpconsul.NewTransportWith(http.DefaultTransport, r)
```

**Comment by achille-roussel** [comment]
This sounds fine to add, you would be available to submit a pull request to make the change?

**Comment by jcheyer** [comment]
Never did before...
There's always a first time, so why not....

**Comment by jcheyer** [comment]
Anything wrong with my pull request ?

**Comment by achille-roussel** [comment]
Thanks for the ping, I had reviewed but forgot to submit the comments, just did!
